Overhauled scripts to match updated original repo

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,30 +1,26 @@
 #!/bin/bash
 
-# Restore IPTABLES rules
-iptables-restore < /etc/iptables.rules
+configdir="/pia"
+tokenfile="$configdir/.token"
+pf_persistfile="$configdir/portsig.json"
 
-# Flush routing table
-
-CONFIGDIR="/pia"
-TOKENFILE="$CONFIGDIR/.token"
-DATAFILE="$CONFIGDIR/data.json"
-
-SHAREDIR="/pia-shared"
-PORTFILE="$SHAREDIR/port.dat"
-
-CURL_MAX_TIME=15
+sharedir="/pia-shared"
+portfile="$sharedir/port.dat"
 
 pia_cacrt="/rsa_4096.crt"
-
-[ $USEMODERN -eq 1 ] && DATAFILE="$CONFIGDIR/data_modern.json"
+wg_conf="/etc/wireguard/wg0.conf"
 
 # Handle shutdown behavior
 finish () {
-    [ $PORT_FORWARDING -eq 1 ] && pkill -f 'pf.sh'
-    echo "$(date): Shutting down Wireguard"
-    [ -w "$PORTFILE" ] && rm "$PORTFILE"
+  [ $PORT_FORWARDING -eq 1 ] && pkill -f 'pf.sh'
+  echo "$(date): Shutting down WireGuard"
+  [ -w "$portfile" ] && rm "$portfile"
+  if [ $WG_USERSPACE -eq 1 ]; then
+    WG_QUICK_USERSPACE_IMPLEMENTATION=wireguard-go wg-quick down wg0
+  else
     wg-quick down wg0
-    exit 0
+  fi
+  exit 0
 }
 
 trap finish SIGTERM SIGINT SIGQUIT
@@ -46,196 +42,58 @@ fatal_error () {
 # Get a new auth token
 # Unsure how long an auth token will remain valid
 get_auth_token () {
-    [ -z "$PASS" ] && echo "$(date): PIA password not set. Unable to retrieve new auth token." && fatal_error
-    [ -z "$USER" ] && echo "$(date): PIA username not set. Unable to retrieve new auth token." && fatal_error
-    echo "$(date): Getting new auth token"
-    TOK=$(curl --silent --show-error --request POST --max-time $CURL_MAX_TIME \
-        --header "Content-Type: application/json" \
-        --resolve "www.privateinternetaccess.com:443:$IP" \
-        --data "{\"username\":\"$USER\",\"password\":\"$PASS\"}" \
-        "https://www.privateinternetaccess.com/api/client/v2/token" | jq -r '.token')
-    [ -z "$TOK" ] && echo "$(date): Failed to acquire new auth token" && fatal_error
-    touch "$TOKENFILE"
-    chmod 600 "$TOKENFILE"
-    echo "$TOK" > "$TOKENFILE"
-    new_auth_token=1
+  [ -z "$PASS" ] && echo "$(date): PIA password not set. Unable to retrieve new auth token." && fatal_error
+  [ -z "$USER" ] && echo "$(date): PIA username not set. Unable to retrieve new auth token." && fatal_error
+  echo "$(date): Generating auth token"
+  /scripts/pia-auth.sh -u "$USER" -p "$PASS" > "$tokenfile"
+  [ $? -ne 0 ] && echo "$(date): Failed to acquire new auth token" && fatal_error
+  chmod 600 "$tokenfile"
 }
 
-# The PIA desktop app uses a public key to verify server list downloads. May as well do the same.
-# https://github.com/pia-foss/desktop/blob/b701601bfa806621a41039514bbb507e250466ec/common/src/jsonrefresher.cpp#L93
-verify_serverlist ()
-{
-    echo "$SERVERLIST" | head -n 1 | tr -d '\n' > /tmp/servers.json
-    echo "$SERVERLIST" | tail -n +3 | base64 -d > /tmp/servers.sig
-    if openssl dgst -sha256 -verify /RegionsListPubKey.pem -signature /tmp/servers.sig /tmp/servers.json; then
-        cp /tmp/servers.json $DATAFILE
-    else
-        echo "$(date): Failed to verify server list"
-        fatal_error
-    fi
-}
+[ -w "$portfile" ] && rm "$portfile"
 
-get_servers () {
-    if [ $USEMODERN -eq 1 ]; then
-        # https://github.com/pia-foss/mobile-common-regions/blob/master/regions/src/commonMain/kotlin/com/privateinternetaccess/common/regions/internals/RegionsCommon.kt#L23
-        if [ ! -r "$DATAFILE" ] || [ $(($(date +%s) - $(date +%s -r $DATAFILE))) -gt 600 ]; then
-            echo "$(date): Fetching and verifying modern PIA server list"
-            SERVERLIST=$(curl --silent --show-error --max-time $CURL_MAX_TIME --resolve "serverlist.piaservers.net:443:$IP" \
-                "https://serverlist.piaservers.net/vpninfo/servers/new")
-            verify_serverlist
-        fi
+# No LOC supplied
+[ -z "$LOC" ] && /scripts/wg-gen.sh -a && fatal_error
 
-        # Some locations have multiple servers available. Pick a random one.
-        TOTALSERVERS=$(jq -r '.regions | .[] | select(.id=="'$LOC'") | .servers.wg | length' $DATAFILE)
-        if ! [[ "$TOTALSERVERS" =~ ^[0-9]+$ ]] || [ $TOTALSERVERS -eq 0 ] 2>/dev/null; then
-            echo "$(date): No matching servers found. Valid servers are:"
-            jq -r '.regions | .[] | .id' "$DATAFILE"
-            fatal_error
-        fi
-        SERVERINDEX=$(( $RANDOM % $TOTALSERVERS))
-        WG_SERIAL=$(jq -r '.regions | .[] | select(.id=="'$LOC'") | .servers.wg | .['$SERVERINDEX'].cn' $DATAFILE)
-        WG_HOST=$(jq -r '.regions | .[] | select(.id=="'$LOC'") | .servers.wg | .['$SERVERINDEX'].ip' $DATAFILE)
-        WG_PORT=$(jq -r '.groups.wg | .[0] | .ports | .[0]' $DATAFILE)
-        WG_DNS=$WG_SERIAL
+[ ! -r "$tokenfile" ] && get_auth_token
 
-        [ $(jq -r '.regions | .[] | select(.id=="'$LOC'") | .port_forward' $DATAFILE) == "true" ] && PORT_FORWARD_AVAIL=1
+# Generate wg0.conf
+/scripts/wg-gen.sh -l "$LOC" -t "$tokenfile" -o "$wg_conf" -k "/RegionsListPubKey.pem" -d "$VPNDNS"
+result=$?
+if [ "$result" -eq 2 ]; then
+  # Reauth and retry if auth failed
+  get_auth_token
+  /scripts/wg-gen.sh -l "$LOC" -t "$tokenfile" -o "$wg_conf" -k "/RegionsListPubKey.pem" -d "$VPNDNS" || fatal_error
+elif [ "$result" -eq 3 ]; then
+  # Location not found
+  echo "$(date): Location $LOC not found"
+  /scripts/wg-gen.sh -a
+  fatal_error
+elif [ "$result" -ne 0 ]; then
+  echo "$(date): Failed to generate WireGuard config"
+  fatal_error
+fi
 
-        [ -z "$WG_HOST" ] && echo "$(date): Wireguard not supported in the selected region ($LOC)" && fatal_error
-
-    else
-        # https://github.com/pia-foss/desktop/blob/754080ce15b6e3555321dde2dcfd0c21ec25b1a9/daemon/src/daemon.cpp#L77
-        # PIA desktop client redownloads server list on launch and then every 10mins.
-        # May as well mimic that behavior.
-        if [ ! -r "$DATAFILE" ] || [ $(($(date +%s) - $(date +%s -r $DATAFILE))) -gt 600 ]; then
-            echo "$(date): Fetching and verifying legacy PIA server list"
-            SERVERLIST=$(curl --silent --show-error --max-time $CURL_MAX_TIME --resolve "www.privateinternetaccess.com:443:$IP" \
-                "https://www.privateinternetaccess.com/vpninfo/servers?version=1001&client=x-alpha")
-            verify_serverlist
-        fi
-        if [ -z "$LOC" ] || [ "$(jq -r .$LOC "$DATAFILE")" == "null" ]; then
-            echo "$(date): No matching servers found. Valid servers are:"
-            jq keys "$DATAFILE"
-            fatal_error
-        fi
-
-        WG_URL=$(jq -r ".$LOC.wireguard.host" "$DATAFILE")
-        WG_SERIAL=$(jq -r ".$LOC.wireguard.serial" "$DATAFILE")
-        WG_HOST=$(cut -d: -f1 <<< "$WG_URL")
-        WG_PORT=$(cut -d: -f2 <<< "$WG_URL")
-        WG_DNS=$(jq -r ".$LOC.dns" "$DATAFILE")
-
-        [ -z "$WG_URL" ] && echo "$(date): Wireguard not supported in the selected region ($LOC)" && fatal_error
-    fi
-}
-
-get_wgconf () {
-    CLIENT_PRIVATE_KEY="$(wg genkey)"
-    CLIENT_PUBLIC_KEY=$(wg pubkey <<< "$CLIENT_PRIVATE_KEY")
-
-    echo "$(date): Registering public key with PIA endpoint $LOC - $WG_DNS ($WG_HOST)"
-
-    # Try to recover from an expired/invalid auth token if we haven't yet got a new one
-    while true; do
-      ADDKEY_RESPONSE=$(curl --get --silent \
-          --data-urlencode "pubkey=$CLIENT_PUBLIC_KEY" \
-          --data-urlencode "pt=$TOK" \
-          --cacert "$pia_cacrt" \
-          --resolve "$WG_SERIAL:$WG_PORT:$WG_HOST" \
-          "https://$WG_SERIAL:$WG_PORT/addKey")
-      [ "$(echo $ADDKEY_RESPONSE | jq -r .status)" == "OK" ] && break
-      if [ $new_auth_token -eq 0 ] && [ "$(echo $ADDKEY_RESPONSE | jq -r .status)" == "ERROR" ] && [ "$(echo $ADDKEY_RESPONSE | jq -r .message)" == "Login failed!" ]; then
-        echo "$(date): Auth failed, regenerating token"
-        get_auth_token
-        continue
-      fi
-      echo "$(date): WG key registration failed" && echo $ADDKEY_RESPONSE && fatal_error
-    done
-
-    PEER_IP="$(echo $ADDKEY_RESPONSE | jq -r .peer_ip)"
-    SERVER_PUBLIC_KEY="$(echo $ADDKEY_RESPONSE | jq -r .server_key)"
-    SERVER_IP="$(echo $ADDKEY_RESPONSE | jq -r .server_ip)"
-    SERVER_VIP="$(echo $ADDKEY_RESPONSE | jq -r .server_vip)"
-    SERVER_PORT="$(echo $ADDKEY_RESPONSE | jq -r .server_port)"
-
-    WGCONF="/etc/wireguard/wg0.conf"
-    echo "$(date): Generating $WGCONF"
-
-    if [ -z "$VPNDNS" ]; then
-        VPNDNS=$(echo $ADDKEY_RESPONSE | jq -r '.dns_servers[0:2]' | grep ^\  | cut -d\" -f2 | xargs echo | sed -e 's/ /,/g')
-        echo "$(date): Using PIA DNS servers: $VPNDNS"
-    else
-        echo "$(date): Using custom DNS servers: $VPNDNS"
-    fi
-
-    cat <<CONFF > "$WGCONF"
-#$WG_DNS
-[Interface]
-PrivateKey = $CLIENT_PRIVATE_KEY
-Address = $PEER_IP
-DNS = $VPNDNS
-
-[Peer]
-PublicKey = $SERVER_PUBLIC_KEY
-AllowedIPs = 0.0.0.0/0
-Endpoint = $SERVER_IP:$SERVER_PORT
-CONFF
-
-    [ $KEEPALIVE -gt 0 ] && echo "PersistentKeepalive = $KEEPALIVE" >> "$WGCONF"
-}
-
-PORT_FORWARD_AVAIL=0
-new_auth_token=0
-
-[ -w "$PORTFILE" ] && rm "$PORTFILE"
-
-[ -r "$TOKENFILE" ] && TOK=$(< "$TOKENFILE")
-[ -z "$TOK" ] && get_auth_token
-
-get_servers
-get_wgconf
-
-[ $PORT_FORWARD_AVAIL -eq 1 ] && echo "$(date): Port forwarding is available on this server"
+# Add PersistentKeepalive if KEEPALIVE is set
+[ $KEEPALIVE -gt 0 ] && echo "PersistentKeepalive = $KEEPALIVE" >> "$wg_conf"
 
 # Bring up Wireguard interface
-echo "$(date): Bringing up Wireguard interface wg0"
-wg-quick up wg0
+echo "$(date): Bringing up WireGuard interface wg0"
+wg-quick up wg0 || fatal_error
 
 # Print out wg interface info
 echo
 wg
 echo
 
-# Use standalone script for port forwarding
-port_forward () {
-  echo "$(date): Starting port forward script"
-  /scripts/pf.sh -t "$TOKENFILE" -i "$SERVER_VIP" -n "$WG_DNS" -p "$PORTFILE" -c "$pia_cacrt" &
-  pf_pid=$!
-  # Standalone script doesn't handle iptables rules, so do that here
-  local pf_port=0
-  local pf_firstrun=1
-  local pf_interval=15
-  while true; do
-    if [ -r "$PORTFILE" ]; then
-      local new_port=$(cat "$PORTFILE")
-      if [ "$pf_port" -ne "$new_port" ]; then
-        if [ $pf_firstrun -ne 1 ]; then
-          [ $PUSH_PORT -eq 1 ] && iptables -D PREROUTING -t nat -i wg0 -p tcp --dport $new_port -j DNAT --to $FORWARD_HOST:$new_port
-          [ $PUSH_PORT -eq 1 ] && iptables -D FORWARD -p tcp -d $FORWARD_HOST --dport $new_port -j ACCEPT
-          echo "$(date): Closing old port"
-          pf_firstrun=0
-        fi
-        [ $PUSH_PORT -eq 1 ] && iptables -A PREROUTING -t nat -i wg0 -p tcp --dport $new_port -j DNAT --to $FORWARD_HOST:$new_port
-        [ $PUSH_PORT -eq 1 ] && iptables -A FORWARD -p tcp -d $FORWARD_HOST --dport $new_port -j ACCEPT
-        echo "$(date): Allowing incoming traffic on port $new_port"
-        [ $MAIL_NOTIFY -eq 1 ] && python3 /scripts/python-mail-notifier/python-mail-notifier.py '$MAILSERVER' $MAILPORT '$MAILUSER' '$MAILPASS' 'WG VPN Port Forwarding Successful' 'Port $new_port forwarded to $FORWARD_HOST:$new_port.' >> /dev/null
-        pf_port="$new_port"
-      fi
-    fi
-    sleep $pf_interval &
-    wait $!
-  done
-}
+echo "$(date): WireGuard successfully started"
 
-[ $PORT_FORWARDING -eq 1 ] && [ $USEMODERN -eq 1 ] && [ $PORT_FORWARD_AVAIL -eq 1 ] && port_forward
+# Setup port forwarding if requested and available
+pf_api_ip=$(grep '#pf api' "$wg_conf"| sed 's/#pf api ip: \(.*\)/\1/')
+pf_cn=$(grep '#cn: ' "$wg_conf"| sed 's/#cn: \(.*\)/\1/')
+if [ $PORT_FORWARDING -eq 1 ] && [ -n "$pf_api_ip" ]; then
+  echo "$(date): Starting port forward script"
+  /scripts/pf.sh -t "$tokenfile" -i "$pf_api_ip" -n "$pf_cn" -p "$portfile" -c "$pia_cacrt" -s "/scripts/pf_success.sh" -r "$pf_persistfile" &
+fi
 
 now_sleep
